name:                reactive-graphs
version:             0.1.0.0
github:              "reactive-graphs/reactive-graphs"
license:             Apache-2.0
author:              "Jeffrey Phillips Freeman"
maintainer:          "the@jeffreyfreeman.me"
copyright:           "2020 Jeffrey Freeman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reactive-graphs/reactive-graphs>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/main/eta

tests:
  reactive-graphs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactive-graphs
